CREATE TABLE nozzle_order (
	work_order VARCHAR(22) NOT NULL, 
	nozzle_number VARCHAR(16) NOT NULL, 
	order_status TINYINT NOT NULL, 
	oil_type TINYINT NOT NULL, 
	oil_category TINYINT NOT NULL, 
	price INTEGER NOT NULL, 
	volume_consume DECIMAL(8,2) NOT NULL, 
	station_code varchar(10) NOT NULL,
	upload_status TINYINT NOT NULL, 
	upload_time VARCHAR(14), 
	PRIMARY KEY (work_order));
CREATE TABLE POS_REG_INFO (
	POS_CODE VARCHAR(10) NOT NULL, 
	PSAM_NUM VARCHAR(20) NOT NULL, 
	POS_STATUS TINYINT NOT NULL, 
	PRIMARY KEY (POS_CODE));
CREATE TABLE nozzle(
	nozzle_number VARCHAR(16) NOT NULL,
	PRIMARY KEY (nozzle_number));
CREATE TABLE oil(
	oil_category TINYINT NOT NULL,
	oil_type TINYINT NOT NULL,
	category_text VARCHAR(16) NOT NULL,
	type_text VARCHAR(16) NOT NULL,
	PRIMARY KEY (oil_category));
CREATE TABLE SHIFT_INFO (ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL , NAME VARCHAR(10) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE oil_station_role(
	id VARCHAR(36) NOT NULL,
	role_name VARCHAR(128) NOT NULL,
	role_desc VARCHAR(128),
	PRIMARY KEY (id),
	UNIQUE (role_name));
CREATE TABLE oil_station_employee(
	id VARCHAR(36) NOT NULL,
	username VARCHAR(32) NOT NULL,
	password VARCHAR(32) NOT NULL,
	status INTEGER NOT NULL,
	last_login_time BIGINT,
	last_login_location VARCHAR(255),
	login_retry_times INTEGER,
	login_failed_delay INTEGER,
	full_name VARCHAR(32),
	email VARCHAR(128),
	phone_num VARCHAR(32),
	user_desc INTEGER,
	login_failed INTEGER,
	frozen_time INTEGER,
	role_id VARCHAR(36),
	PRIMARY KEY (id),
	UNIQUE (username));
CREATE TABLE oil_station(
	code VARCHAR(20) NOT NULL,
	name VARCHAR(64) NOT NULL,
	status INTEGER NOT NULL,
	address VARCHAR(128),
	telephone VARCHAR(20),
	manager VARCHAR(36),
	owner_code VARCHAR(36),
	established_date VARCHAR(10),
	PRIMARY KEY (code));
INSERT INTO OIL (OIL_CATEGORY, OIL_TYPE, CATEGORY_TEXT, TYPE_TEXT) VALUES (1, 1, '92#汽油', '汽油');
INSERT INTO OIL (OIL_CATEGORY, OIL_TYPE, CATEGORY_TEXT, TYPE_TEXT) VALUES (2, 1, '95#汽油', '汽油');
INSERT INTO OIL (OIL_CATEGORY, OIL_TYPE, CATEGORY_TEXT, TYPE_TEXT) VALUES (3, 1, '98#汽油', '汽油');
INSERT INTO OIL (OIL_CATEGORY, OIL_TYPE, CATEGORY_TEXT, TYPE_TEXT) VALUES (31, 2, '0#柴油', '柴油');
INSERT INTO OIL (OIL_CATEGORY, OIL_TYPE, CATEGORY_TEXT, TYPE_TEXT) VALUES (32, 2, '-10#柴油', '柴油');

INSERT INTO SHIFT_INFO (ID, NAME) VALUES (1, '早班');
INSERT INTO SHIFT_INFO (ID, NAME) VALUES (2, '中班');
INSERT INTO SHIFT_INFO (ID, NAME) VALUES (3, '晚班');

